
jobs:
  - job: testingDownloadPipelineArtifact
    displayName: 'testing pipelines'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: export SYSTEM_DEBUG=true
      - task: DownloadPipelineArtifact@1
        displayName: 'Download server artifact files'
        inputs:
          buildType: 'specific'
          project: 'test mariadb ent'
          pipeline: 'rusher.MariaDBEnterprise'
          artifactName: 'ent-pipe-ubuntu-1604'
          #buildVersionToDownload: 'latest'
          buildId: 1
          buildVersionToDownload: 'specific'
          downloadPath: $(System.DefaultWorkingDirectory)
        env:
          SYSTEM_DEBUG: true
